### ISSUE TITLE
Errors in promises after deployment of 0.1

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager2#55]

**Comment by fabienDaou** [comment]
`Error: response.data.championsAffinity is undefined
[15]</module.exports/</<.setPerformances/a/<@http://lolmanager.herokuapp.com/bundle.js:1271:7
f/<@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:118:217
kf/this.$get</m.prototype.$eval@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:132:354
kf/this.$get</m.prototype.$digest@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:129:357
kf/this.$get</m.prototype.$apply@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:133:111
g@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:87:338
L@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:91:406
Sf/</A.onload@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:92:437
 angular.min.js:107:50

Error: response.data.championsAffinity is undefined
[15]</module.exports/</<.setPerformances/a/<@http://lolmanager.herokuapp.com/bundle.js:1284:7
f/<@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:118:217
kf/this.$get</m.prototype.$eval@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:132:354
kf/this.$get</m.prototype.$digest@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:129:357
kf/this.$get</m.prototype.$apply@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:133:111
g@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:87:338
L@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:91:406
Sf/</A.onload@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js:92:437
 angular.min.js:107:50
`

Who does that???

**Comment by Gollwu** [comment]
Need to refactor services to not return the variable.

**Comment by Gollwu** [comment]
Fixed and deployed. App now running fine.
